# example netlify.toml
[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "public"

## Uncomment to use this redirect for Single Page Applications
## Not needed for static site generators.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200